### PR TITLE
Replace legacy start api in favor of updates api

### PR DESCRIPTION
**Pull request by pradeepgv-db**
Replace legacy start api in favor of updates api in databricks cli.

### CODE REVIEW

**Review by enzam-db — APPROVED** [review]

**Review by anew — APPROVED** [review]

**Comment by pradeepgv-db** [comment]
jenkins merge

**Comment by pradeepgv-db** [comment]
@mukulmurthy could you help with merging this in?

**Review by pietern — APPROVED** [review]

**Comment by pietern** [comment]
@pradeepgv-db You can ping me for following changes.

**Comment by mukulmurthy** [comment]
I was on-call and am just catching up on emails now. Was prioritizing code reviews, but I guess I didn't have docs PRs tagged with the right label. Sorry for the delay!

**Pull request merged**
