### PR TITLE
Add insecure option to configure

### PR DESCRIPTION
**Pull request by andrewmchen**
We would like to use the CLI against shards without proper SSL certificates. (For development purposes.)

### CODE REVIEW

**Comment by ericwang-db** [comment]
@andrewmchen Nice! Why did you prefer to make this a config option vs a command line option that's per command invocation (like `--profile`). That seems to be more in line with CURL behavior, and makes the lack of trust more explicit.

**Comment by andrewmchen** [comment]
IMO, that doesn't make a lot of sense. Whether or not the host has SSL set up correctly is super coupled to the profile so it should be configured with the profile I think.

**Comment by ericwang-db** [comment]
@andrewmchen looks good! However, could we make `insecure` not show up in ~/.databrickscfg when it is set to None? That happens for username/password when switching the default config to token-based auth.

**Comment by ericwang-db** [comment]
@andrewmchen made a change to make ^ happen. https://github.com/ericwang-db/databricks-cli/commit/81abbeee520851be6f3dcef5092a5ae9063cbd8a

Could you cherry-pick and let's close this PR?

**Comment by ericwang-db** [comment]
lgtm

**Pull request merged**
