### PR TITLE
Adding the new python 3.7 to testing

### LINKED ISSUE #141: Support python 3.7
Probably works as is, but should be added to tests

### PR DESCRIPTION
**Pull request by alonisser**
close #141

### CODE REVIEW

**Comment by alonisser** [comment]
Seems that travisci doesnot support python 3.7 yet (besides dev), I'll check with them

**Comment by diraol** [comment]
The problem is not with travis.

The real problem is that `flake8` is taking a long time to have a new release and support the most updated version of `pycodestyle`. That's why we can see this warning on travis output: 

```
/home/travis/build/databricks/databricks-cli/.tox/py37/lib/python3.7/site-packages/pycodestyle.py:111: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
```
(This Exception has already been fixed on the newer pycodestyle version AFAIK).

https://gitlab.com/pycqa/flake8/issues/426#note_91449052

**Comment by alonisser** [comment]
@diraol The problem "was" with travis in the beginning, but was fixed when I specified running the build on xenial (they don't support 3.7 for less) but I was wrestling with the flake8 issue and failing to resolve it

**Comment by Trollgeir** [comment]
What's the status on this? I'm currently being blocked by:

https://issues.apache.org/jira/browse/SPARK-26067?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel

**Comment by pietern** [comment]
This is fixed by using GitHub Actions (see #463) and testing against all stable Python versions (see #467).

Thanks for raising this issue in the first place, @alonisser.

**Pull request closed without merging**
