### PR TITLE
Revert "Sample - Fix exports from Workspace to Windows FS (#448)"

### PR DESCRIPTION
**Pull request by pietern**
This reverts commit c695b8db92917f18bf3d6a6a22acc88fe743a3e2.

See https://github.com/databricks/databricks-cli/pull/448#issuecomment-1181692483.

### CODE REVIEW

**Comment by pietern** [comment]
Thanks, @stormwindy. Is there an issue for this already? If not, could you create one with the exact incompatibility you're thinking about? E.g. is this just about forward vs backward slash or more incompatible characters?

**Comment by stormwindy** [comment]
@pietern There used to be an issue from a contributor. However, I couldn't find it again (it was about downloading job results from what I remember). There is another one recently created issue about characters not being compatible: https://github.com/databricks/databricks-cli/issues/366

**Comment by stormwindy** [comment]
@pietern I created this for following the issue https://github.com/databricks/databricks-cli/issues/517

**Comment by pietern** [comment]
@stormwindy Thank you!

**Pull request merged**
