### PR TITLE
Add support to get and update permissions on a Metastore

### PR DESCRIPTION
**Pull request by wchau**

### CODE REVIEW

**Review by adamcain-db — APPROVED** [review]
LGTM!
BTW, a couple weeks ago I asked @allisonwang-db about adding `FUNCTION` and she said they didn't have a use case yet for adding that support to databricks-cli.

**Comment by wchau** [comment]
> LGTM! BTW, a couple weeks ago I asked @allisonwang-db about adding `FUNCTION` and she said they didn't have a use case yet for adding that support to databricks-cli.

We also have share, recipient, and provider, but don't need permissions for them yet.

**Review by fjakobs — APPROVED** [review]
LGTM

**Comment by fjakobs** [comment]
@wchau please configure commit signing then it's ready to merge.
https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification

**Comment by wchau** [comment]
@fjakobs Done!

**Pull request merged**
