### PR TITLE
Python 3 compatibility

### LINKED ISSUE #2: CLI does not work with python 3
I get the following error 

`Traceback (most recent call last):
  File "/usr/local/bin/dbfs", line 7, in <module>
    from databricks_cli.dbfs.cli import dbfs_group
  File "/usr/local/lib/python3.6/site-packages/databricks_cli/dbfs/cli.py", line 31, in <module>
    from databricks_cli.configure.cli import configure_cli
  File "/usr/local/lib/python3.6/site-packages/databricks_cli/configure/cli.py", line 29, in <module>
    from databricks_cli.configure.config import DatabricksConfig
  File "/usr/local/lib/python3.6/site-packages/databricks_cli/configure/config.py", line 24, in <module>
    import ConfigParser
ModuleNotFoundError: No module named 'ConfigParser'`

### PR DESCRIPTION
**Pull request by andreabedini**
Mostly boring stuff. The hardest part was figuring out the test suite was causing havoc in the request package by creating a `Request` object with a string as `_content` rather than bytes. Included Dockerfile for Python 3. Test suite passes both in Python 2/3 🍻 

Fixes #2.

PS: I left in a change of the Dockerfile that allows caching the requirements. Let me know if you want me to pull that out.

### CODE REVIEW

**Comment by andrewmchen** [comment]
Thanks for the great work! Before we make the new release, we'll also need to make sure our travis test runner can test on Python 3. Could you add something [here](https://github.com/databricks/databricks-cli/blob/master/.travis.yml)?

https://docs.travis-ci.com/user/languages/python/

**Comment by andreabedini** [comment]
@aarondav oh, I didn't notice the travis file. I now added a bunch of Pythons, let's see if it works :P

**Comment by andrewmchen** [comment]
Seems like `databricks workspace ls` doesn't work?
https://stackoverflow.com/questions/13361510/typeerror-unsupported-operand-types-for-dict-items-and-dict-items

**Comment by andreabedini** [comment]
> Seems like databricks workspace ls doesn't work?
> https://stackoverflow.com/questions/13361510/typeerror-unsupported-operand-types-for-dict-items-and-dict-items

Sorry @andrewmchen I was just going along with the provided test suite ... do you have a backtrace?

I get something else
```
♥ ~/code/databricks-cli databricks workspace ls
Error: TypeError: a bytes-like object is required, not 'str'
```
with no stack trace, it must get swallowed somewhere ... do you have hints?

**Comment by andreabedini** [comment]
oh, never mind, I found it `databricks_cli.utils.eat_exceptions` ... 💃

**Comment by andrewmchen** [comment]
Yeah unforunately, the test coverage from the provided test suite leaves something to be desired. It'd be important to improve the coverage before we officially release python 3 support.

**Comment by andreabedini** [comment]
@andrewmchen I know you're using `six` already but would you be open to use `python-future` instead? that would allow you to write clean Py3 code while making sure it works on older Pythons. My 2c. It also has an automatic converter that can be useful.

**Comment by andrewmchen** [comment]
Yeah I'm totally open to using `python-future`. Do people normally use one or the other or can you use `python-future` in conjunction with `six`?

**Comment by andreabedini** [comment]
hey @andrewmchen, happy new year 🎉 🎆 
I rebased the branch with the code auto-translated by the python-future package. Ideally this should allow you to write Python3 and have it running seamlessly on Python2. The only problem is that the linter freaks out :) by the redefinition of the built-ins.

Give it a go.

**Comment by andrewmchen** [comment]
Sorry for letting this PR languish. The PR looks really nice but I think we need some better test coverage for the CLI in the form of some integration tests before I'm comfortable merging this PR. This is something we're planning to add soon so look out!

Also FYI, the file `databricks_cli/sdk/service.py` is autogenerated so be careful editing that. We may have to modify that upstream in the autogenerator.

**Comment by andreabedini** [comment]
@andrewmchen sounds like a good plan :) ping me when/if you need input

**Comment by mengxr** [comment]
@andrewmchen @andreabedini I'm closing this PR because the PY3 support was merged. Thanks for the work!

**Pull request closed without merging**
